"""
Athar Output Envelope Schema

Unified output wrapper for all pipeline tools. Ensures consistent
artifact tracking, reporting, and workflow orchestration.
"""

from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Literal, Any
from datetime import datetime
from enum import Enum


class Visibility(str, Enum):
    """Artifact visibility classification."""
    PRIVATE = "private"  # Never exposed publicly
    PUBLIC = "public"    # Can be deployed to Firebase Hosting


class ArtifactType(str, Enum):
    """Types of artifacts produced by the pipeline."""
    MANUSCRIPT = "manuscript"
    STYLE_REPORT = "style_report"
    PROOF_REPORT = "proof_report"
    PDF_FULL = "pdf_full"
    PDF_SAMPLE = "pdf_sample"
    EPUB_FULL = "epub_full"
    EPUB_SAMPLE = "epub_sample"
    READER_BUNDLE = "reader_bundle"
    RELEASE_MANIFEST = "release_manifest"
    COVER_IMAGE = "cover_image"
    OTHER = "other"


class Artifact(BaseModel):
    """An artifact produced by a pipeline tool."""
    id: str = Field(..., description="Unique artifact identifier")
    type: ArtifactType = Field(..., description="Type of artifact")
    path: str = Field(..., description="Storage path relative to storage root")
    visibility: Visibility = Field(default=Visibility.PRIVATE)
    checksum: Optional[str] = Field(default=None, description="SHA-256 checksum")
    size_bytes: Optional[int] = Field(default=None)
    mime_type: Optional[str] = Field(default=None)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    metadata: Optional[dict] = Field(default=None, description="Additional artifact metadata")


class Severity(str, Enum):
    """Issue severity levels."""
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


class ReportItem(BaseModel):
    """Individual item within a report."""
    id: str = Field(..., description="Unique item identifier")
    severity: Severity = Field(default=Severity.INFO)
    category: str = Field(..., description="Category (e.g., 'grammar', 'style', 'formatting')")
    message: str = Field(..., description="Human-readable message")
    location: Optional[str] = Field(default=None, description="Location reference (e.g., chapter/section)")
    suggestion: Optional[str] = Field(default=None, description="Suggested fix")
    resolved: bool = Field(default=False)


class Report(BaseModel):
    """A report generated by a pipeline tool."""
    id: str = Field(..., description="Unique report identifier")
    type: str = Field(..., description="Report type (e.g., 'style_suggestions', 'proof_pass_1')")
    title: str = Field(..., description="Human-readable title")
    items: List[ReportItem] = Field(default_factory=list)
    summary: Optional[str] = Field(default=None)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    @property
    def critical_count(self) -> int:
        return sum(1 for item in self.items if item.severity == Severity.CRITICAL and not item.resolved)
    
    @property
    def error_count(self) -> int:
        return sum(1 for item in self.items if item.severity == Severity.ERROR and not item.resolved)
    
    @property
    def has_blocking_issues(self) -> bool:
        return self.critical_count > 0 or self.error_count > 0


class NextAction(BaseModel):
    """Suggested next action in the pipeline."""
    action: str = Field(..., description="Action identifier")
    description: str = Field(..., description="Human-readable description")
    required: bool = Field(default=False, description="Whether this action is required before proceeding")
    target_agent: Optional[str] = Field(default=None, description="Agent that should handle this action")
    parameters: Optional[dict] = Field(default=None, description="Parameters for the action")


class AtharOutputEnvelope(BaseModel):
    """
    Unified output envelope for all Athar pipeline tools.
    
    Every tool returns this envelope to ensure consistent artifact tracking,
    reporting, and workflow orchestration.
    """
    version: str = Field(default="1.0.0", description="Envelope schema version")
    
    # Job metadata
    job_id: str = Field(..., description="Unique job/request identifier")
    project_id: str = Field(..., description="Project/manuscript identifier")
    tool_name: str = Field(..., description="Name of the tool that produced this output")
    stage: str = Field(..., description="Pipeline stage (e.g., 'ingestion', 'editing', 'formatting')")
    
    # Execution info
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = Field(default=None)
    success: bool = Field(default=True)
    
    # Outputs
    artifacts: List[Artifact] = Field(default_factory=list)
    reports: List[Report] = Field(default_factory=list)
    next_actions: List[NextAction] = Field(default_factory=list)
    
    # Errors
    errors: List[str] = Field(default_factory=list)
    
    # Raw output data (tool-specific)
    data: Optional[Any] = Field(default=None, description="Tool-specific output data")
    
    def add_artifact(self, artifact: Artifact) -> None:
        """Add an artifact to the envelope."""
        self.artifacts.append(artifact)
    
    def add_report(self, report: Report) -> None:
        """Add a report to the envelope."""
        self.reports.append(report)
    
    def add_error(self, error: str) -> None:
        """Add an error and mark as failed."""
        self.errors.append(error)
        self.success = False
    
    def has_blocking_issues(self) -> bool:
        """Check if any reports have blocking issues."""
        return any(report.has_blocking_issues for report in self.reports)
    
    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "version": "1.0.0",
                "job_id": "job-12345",
                "project_id": "athar-book-001",
                "tool_name": "ManuscriptCompilerTool",
                "stage": "ingestion",
                "success": True,
                "artifacts": [
                    {
                        "id": "art-001",
                        "type": "manuscript",
                        "path": "private/manuscripts/athar-book-001.json",
                        "visibility": "private"
                    }
                ],
                "next_actions": [
                    {
                        "action": "style_edit",
                        "description": "Run style editor on manuscript",
                        "target_agent": "style_editor"
                    }
                ]
            }
        }
    )
